### ISSUE TITLE
添加子节点500错误

### ISSUE THREAD

**Issue by KennethHoo** [CubeWhyMC/DingZhenServlet#11]
主控面板添加子节点时
`{
    "timestamp": "2024-10-17T06:21:51.582+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/admin/gateway/add"
}`
req:
`{"name":"123456","address":"http://141.X1.XX.XXX:8080","key":"JTvsfXXXXXXXXXXmQVzTGfO1Ch3xOZT0="}`
在机房，无主控日志

**Comment by KennethHoo** [comment]
额，似乎加了。

**Comment by KennethHoo** [comment]
不知道是否生效，

**Comment by cubewhy** [comment]
fixed
